version: '3.1'

services:

  mdedef:
    #build: .
    image: esurveillance/mdedefinitions
    restart: always
    container_name: mdedefinition
    ports:
      - 10000:10000
    links:
      - mongodb_mde
    depends_on:
      - mongodb_mde
    networks:
      - esurv1

  mongodb_mde:
      image: mongo:latest
      container_name: "mongodb_mde"
      environment:
        - MONGO_DATA_DIR=/data/mde_db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - ./data/mde_db:/data/db
      ports:
          - 27018:27017
      command: mongod --smallfiles --logpath=/dev/null # --quiet
      networks:
        - esurv1

networks:
  esurv1:
    driver: bridge
