server:
  servlet:
    context-path: /serviceContext
  port: 10000
  apiContext:
  versionContext: v

spring:
  application:
    name: <SERVICE>-Service

  profiles:
    active: ${SPRING_PROFILE}


  data:
    mongodb:
      uri: mongodb://localhost:27017/mde_definitions

eip-service-config:
  pageInfo:
    maxPageSize: 100
    defaultPageSize: 20


about:
  summary: This is a stub for starting Spring REST RENAME_ME. It includes basic Boot configuration, Docker, and a About service that reads this YAML file.
  docs: http://localhost:${server.port}${server.servlet.context-path}/swagger-ui.html

  versions:
    - v1
  contacts:
    -
      name: Marcelo Caldas
      email: mcq1@cdc.gov
      role: Soft. Architect

---
spring:
  profiles: DOCKER

  data:
    mongodb:
      uri: mongodb://mongodb:27017/mde_definitions

---
spring:
  profiles: QA



---
spring:
  profiles: STG


---
spring:
  profiles: PROD
